name: hh_sdk_unofficial
description: https://api.hh.ru/openapi/redoc
version: 1.0.0
repository: https://github.com/i-panov/dart_hh_sdk_unofficial

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.8.0+1
  fast_immutable_collections: ^11.0.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.10.0
